export const tokens = {
  colors: {
    primary: '#6c5b4d',
    primaryHover: '#5f5042',
    secondary: '#625f59',
    background: '#faf9f6',
    surfaceContainer: '#edeeea',
    surfaceContainerLow: '#f4f4f0',
    surfaceContainerHighest: '#e0e4de',
    surfaceWhite: '#ffffff',
    primaryContainer: '#f5decd',
    text: '#2f3430',
    textSecondary: '#5c605c',
    onPrimary: '#fff6f1',
    border: '#afb3ae',
  },
  fonts: {
    primary: "'Plus Jakarta Sans', sans-serif",
    heading: "'Manrope', sans-serif",
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 8,
    md: 16,
    lg: 24,
    xl: 48,
    full: 9999,
  },
} as const;
